prueba_admin_usuarios:
    resource: "@PruebaBundle/Resources/config/routing/usuarios.yml"
    prefix:   /admin/usuarios/
prueba_admin_productos:
    resource: "@PruebaBundle/Resources/config/routing/productos.yml"
    prefix:   /admin/productos/
prueba_admin_ficha:
    resource: "@PruebaBundle/Resources/config/routing/ficha_tecnica.yml"
    prefix:   /admin/ficha/


prueba_homepage:
    path:     /
    defaults: { _controller: PruebaBundle:Default:index }
    
prueba_buscar:
     path:     /productos/buscar
     defaults: { _controller: PruebaBundle:Producto:buscarProducto }




mensaje_producto:
     path:     /productos/mensaje
     defaults: { _controller: PruebaBundle:Producto:mensajeProducto }


prueba_ficha:
     path:     /productos/ficha
     defaults: { _controller: PruebaBundle:Producto:fichaProducto }
     
prueba_second:
    path:     /second
    defaults: { _controller: PruebaBundle:Default:second }
prueba_contactos:
    path:     /contactos
    defaults: { _controller: PruebaBundle:Default:contactos }
prueba_login:
    path:     /login
    defaults: { _controller: PruebaBundle:Default:login }
    
productos:
    path:     /productos
    defaults: { _controller: PruebaBundle:Producto:all }

registro:
    path:     /registro
    defaults: { _controller: PruebaBundle:Default:registro }
ingresoprod:
    path:     /admin/ingresoprod
    defaults: { _controller: PruebaBundle:Producto:dibujarFormProducto }

ingresofichaprod:
    path:     /admin/ingresoficha
    defaults: { _controller: PruebaBundle:Producto:dibujarFormFicha }

mensaje:
    path:     /mensaje
    defaults: { _controller: PruebaBundle:Producto:mensaje }
    
    

modeloingresoprod:
    path:    /admin/modeloingresoprod
    defaults: { _controller: PruebaBundle:Producto:modcrearProducto }
    
administrador:
    path:     /administrador
    defaults: { _controller: PruebaBundle:Default:registroAdminregiste }

register_user:
    path:     /admin/ingresouser
    defaults: { _controller: PruebaBundle:User:register }