admin_ficha_index:
    path:     /
    defaults: { _controller: "PruebaBundle:Ficha_Tecnica:index" }
    methods:  GET

admin_ficha_show:
    path:     /{id}/show
    defaults: { _controller: "PruebaBundle:Ficha_Tecnica:show" }
    methods:  GET

admin_ficha_new:
    path:     /new
    defaults: { _controller: "PruebaBundle:Ficha_Tecnica:new" }
    methods:  [GET, POST]

admin_ficha_edit:
    path:     /{id}/edit
    defaults: { _controller: "PruebaBundle:Ficha_Tecnica:edit" }
    methods:  [GET, POST]

admin_ficha_delete:
    path:     /{id}/delete
    defaults: { _controller: "PruebaBundle:Ficha_Tecnica:delete" }
    methods:  DELETE
