admin_localizacion_index:
    path:     /
    defaults: { _controller: "PruebaBundle:Localizacion:index" }
    methods:  GET

admin_localizacion_show:
    path:     /{id}/show
    defaults: { _controller: "PruebaBundle:Localizacion:show" }
    methods:  GET

admin_localizacion_new:
    path:     /new
    defaults: { _controller: "PruebaBundle:Localizacion:new" }
    methods:  [GET, POST]

admin_localizacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "PruebaBundle:Localizacion:edit" }
    methods:  [GET, POST]

admin_localizacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "PruebaBundle:Localizacion:delete" }
    methods:  DELETE
