admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

prueba:
    resource: "@PruebaBundle/Resources/config/routing.yml"
    prefix:   /

proyecto:
    resource: "@proyectoBundle/Resources/config/routing.yml"
    prefix:   /proyecto

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout