<?php

namespace PruebaBundle\Repository;

/**
 * Ficha_TecnicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ficha_TecnicaRepository extends \Doctrine\ORM\EntityRepository
{
}
