<?php

namespace PruebaBundle\Repository;

/**
 * LocalizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
